# Generated by Django 4.2.27 on 2026-01-08 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='firstapp/')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('EL', 'ELACHI'), ('PL', 'PLAIN')], default='ML', max_length=100)),
            ],
        ),
    ]
